go_import_path: github.com/Neur0toxine/bash.im-telegram-bot
dist: xenial
language: go
cache:
  directories:
    - $HOME/.cache/go-build
    - $HOME/gopath/pkg
go:
  - "1.12"
script:
  - "go test ./src"
  - "cd ./src && go build -o ./../build/bash_im_bot"
env:
  - GO111MODULE=on
install: 
  - export GOPATH="$GOPATH:${TRAVIS_BUILD_DIR}"