dist: xenial
language: go
go_import_path: github.com/Neur0toxine/bash.im-telegram-bot
cache:
  directories:
    - $HOME/.cache/go-build
    - $HOME/gopath/pkg/mod
go:
  - "1.12"
script:
  - "make test"
  - "make build"